export const AUDIO_WALL_HIT="wall_hit.wav";
export const AUDIO_PADDLE_HIT="paddle_1.wav";
export const AUDIO_GOAL_SCORED="goal_1.wav";

export const TAG_WALL_HIT ="ball_drop";
export const TAG_PADDLE_HIT ="paddle_hit";
export const TAG_GOAL_SCORED ="goal_scored";
export const TAG_AMBIENT_LIGHT ="ambientLight";
export const TAG_DIRECTIONAL_LIGHT ="directionalLight";
export const TAG_CAMERA ="camera";
export const TAG_OUTSIDE ="outside";
export const TAG_PLAYER ="player";
export const TAG_OPPONENT ="opponent";
export const TAG_BOTTOM_WALL ="bottomWall";
export const TAG_TOP_WALL ="topWall";
export const TAG_BALL ="ball";
export const TAG_OPPONENT_SCORE ="opponentScore";
export const TAG_PLAYER_SCORE ="playerScore";
export const TAG_COURT = "court";